use inkscape to convert graphics when available as it does a better job

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -16,7 +16,7 @@ usbview_SOURCES =		\
 	configure-dialog.c      \
 	usbview_logo.xpm
 
-interface.o: $(src_icon_bitmap)
+interface.o: $(icon_bitmaps_xpm)
 
 EXTRA_DIST = $(man_MANS) usbview_icon.svg usbview.spec usbview_logo.xcf
 
@@ -27,7 +27,7 @@ endif
 
 icondir = $(datadir)/icons
 
-icon_bitmaps = \
+icon_bitmaps_png = \
        hicolor/16x16/apps/usbview.png \
        hicolor/22x22/apps/usbview.png \
        hicolor/32x32/apps/usbview.png \
@@ -35,15 +35,33 @@ icon_bitmaps = \
        hicolor/64x64/apps/usbview.png \
        hicolor/256x256/apps/usbview.png
 
-src_icon_bitmap = hicolor/64x64/apps/usbview_icon.xpm
+icon_bitmaps_xpm = hicolor/64x64/apps/usbview_icon.xpm
 
 if ICONS
-nobase_icon_DATA = $(icon_scalable) $(icon_bitmaps)
+nobase_icon_DATA = $(icon_scalable) $(icon_bitmaps_png)
 endif
 
-$(icon_bitmaps) $(src_icon_bitmap): usbview_icon.svg
+$(icon_bitmaps_png): usbview_icon.svg
 	mkdir -p $$(dirname $@)
-	convert -geometry $$(basename $$(dirname $$(dirname $@))) $< $@
+if USE_INKSCAPE
+	$(INKSCAPE) --export-png=$@ --export-width=$$(basename $$(dirname $$(dirname $@))) $<
+else
+if USE_CONVERT
+	$(CONVERT) -geometry $$(basename $$(dirname $$(dirname $@))) $< $@
+else
+	echo "error: unable to generate $@ from $<"
+	exit 1
+endif
+endif
+
+$(icon_bitmaps_xpm): usbview_icon.svg
+	mkdir -p $$(dirname $@)
+if HAVE_CONVERT
+	$(CONVERT) -geometry $$(basename $$(dirname $$(dirname $@))) $< $@
+else
+	echo "error: unable to generate $@ from $<"
+	exit 1
+endif
 
 icon_scalable = hicolor/scalable/apps/usbview.svg
 
@@ -51,7 +69,7 @@ $(icon_scalable): usbview_icon.svg
 	mkdir -p $$(dirname $@)
 	cp $< $@
 
-CLEANFILES = $(icon_scalable) $(icon_bitmaps) $(src_icon_bitmap)
+CLEANFILES = $(icon_scalable) $(icon_bitmaps_png) $(icon_bitmaps_xpm)
 
 # gtk_update_icon_cache = gtk-update-icon-cache -f -t $(datadir)/icons/hicolor; gtk-update-icon-cache -f -t $(datadir)/icons/HighContrast
 #
