scalable icon and desktop file support
Convert xpm bitmap icon into a scalable svg icon (carefully sized to
64x64 and saved as plain SVG instead of inkscape-extended SVG)

Add a .desktop file.

Have Makefile.am install the desktop file and icons, including bitmap
icons at various resolutions.  This is controlled by configuration-time
option ./configure --enable-icons for conditional installation of icons
and desktop file.  Inkscape is used to convert graphics when available
as it does a better job than ImageMagick convert, which is used as a
fallback.

The icon compiled into the executable is also generated from the
scalable icon.

Add usbview.desktop to distribution tarball.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -14,9 +14,72 @@ usbview_SOURCES =		\
 	usbtree.c usbtree.h	\
 	usbparse.c usbparse.h	\
 	configure-dialog.c      \
-	usbview_logo.xpm	\
-	usbview_logo.xcf	\
-	usb_icon.xpm		\
-	usbview.spec
+	usbview_logo.xpm
 
-EXTRA_DIST = $(man_MANS)
+interface.o: $(icon_bitmaps_xpm)
+
+EXTRA_DIST = $(man_MANS) usbview_icon.svg usbview.desktop usbview.spec usbview_logo.xcf
+
+desktopdir = $(datadir)/applications
+if DESKTOP
+desktop_DATA = usbview.desktop
+endif
+
+icondir = $(datadir)/icons
+
+icon_bitmaps_png = \
+       hicolor/16x16/apps/usbview.png \
+       hicolor/22x22/apps/usbview.png \
+       hicolor/32x32/apps/usbview.png \
+       hicolor/48x48/apps/usbview.png \
+       hicolor/64x64/apps/usbview.png \
+       hicolor/256x256/apps/usbview.png
+
+icon_bitmaps_xpm = hicolor/64x64/apps/usbview_icon.xpm
+
+if ICONS
+nobase_icon_DATA = $(icon_scalable) $(icon_bitmaps_png)
+endif
+
+$(icon_bitmaps_png): usbview_icon.svg
+	mkdir -p $$(dirname $@)
+if USE_INKSCAPE
+	$(INKSCAPE) --export-png=$@ --export-width=$$(basename $$(dirname $$(dirname $@))) $<
+else
+if USE_CONVERT
+	$(CONVERT) -geometry $$(basename $$(dirname $$(dirname $@))) $< $@
+else
+	echo "error: unable to generate $@ from $<"
+	exit 1
+endif
+endif
+
+$(icon_bitmaps_xpm): usbview_icon.svg
+	mkdir -p $$(dirname $@)
+if HAVE_CONVERT
+	$(CONVERT) -geometry $$(basename $$(dirname $$(dirname $@))) $< $@
+else
+	echo "error: unable to generate $@ from $<"
+	exit 1
+endif
+
+icon_scalable = hicolor/scalable/apps/usbview.svg
+
+$(icon_scalable): usbview_icon.svg
+	mkdir -p $$(dirname $@)
+	cp $< $@
+
+CLEANFILES = $(icon_scalable) $(icon_bitmaps_png) $(icon_bitmaps_xpm)
+
+# gtk_update_icon_cache = gtk-update-icon-cache -f -t $(datadir)/icons/hicolor; gtk-update-icon-cache -f -t $(datadir)/icons/HighContrast
+#
+# install-data-hook: update-icon-cache
+# uninstall-hook: update-icon-cache
+# update-icon-cache:
+#	@-if test -z "$(DESTDIR)"; then \
+#		echo "Updating Gtk icon cache."; \
+#		$(gtk_update_icon_cache); \
+#	else \
+#		echo "*** Icon cache not updated.  After (un)install, run this:"; \
+#		echo "***   $(gtk_update_icon_cache)"; \
+#	fi
